plugins {
    id 'buildlogic.java-conventions'
}

dependencies {
    api project(':lib-core')
}

description = 'autoconfigure-core'

publishing {
    publications {
        maven(MavenPublication) {
            artifactId = description
            from(components.java)
        }
    }
}

bootJar {
    enabled = false
}
