plugins {
    id 'buildlogic.java-conventions'
}

description = 'lib-mysql'

dependencies {
    def mysqlConnectorJ= '9.1.0'

    implementation 'com.mysql:mysql-connector-j:' + mysqlConnectorJ
}

publishing {
    publications {
        maven(MavenPublication) {
            artifactId = description
            from(components.java)
        }
    }
}
