plugins {
    id 'buildlogic.java-conventions'
}

dependencies {
    api project(':starter-core')
    api project(':starter-web')
    api project(':autoconfigure-jpa')
    api project(':lib-jpa')
}

description = 'presto-jpa-spring-boot-starter'

publishing {
    publications {
        maven(MavenPublication) {
            artifactId = description
            from(components.java)
        }
    }
}
