plugins {
    id 'java'
    id 'java-library'
    id 'maven-publish'
    id 'groovy-gradle-plugin'
    id 'org.springframework.boot'
}

group = 'com.prosilion.presto'
version = '0.0.3-SNAPSHOT'
description = 'presto'

java.sourceCompatibility = JavaVersion.VERSION_21
java.targetCompatibility = JavaVersion.VERSION_21

repositories {
    gradlePluginPortal()
    mavenLocal()
    mavenCentral()
    maven {
        url = uri('https://repo.maven.apache.org/maven2/')
    }
}

publishing {
    publications {
//        TODO: gradle vs maven publishing diffs
/**
 
        dir structure diffs:
        maven:
          /home/nick/.m2/repository/com/prosilion/presto/autoconfigure/azure/0.0.3-SNAPSHOT:
        
        gradle:
          /home/nick/.m2/repository/com/prosilion/presto/autoconfigure-azure/0.0.3-SNAPSHOT:

        dir content diffs::
        maven:        
         -rw-rw-r-- 1 nick nick 5759 Mar 16 23:16 azure-0.0.3-SNAPSHOT.jar
         -rw-rw-r-- 1 nick nick 1448 Mar 15 22:53 azure-0.0.3-SNAPSHOT.pom
         -rw-rw-r-- 1 nick nick  725 Mar 16 23:16 maven-metadata-local.xml
         -rw-rw-r-- 1 nick nick  194 Mar 16 23:16 _remote.repositories
 
        gradle
         -rw-rw-r-- 1 nick nick 5807 Mar 16 23:04 autoconfigure-azure-0.0.3-SNAPSHOT.module
         -rw-rw-r-- 1 nick nick 4371 Mar 16 23:04 autoconfigure-azure-0.0.3-SNAPSHOT-plain.jar
         -rw-rw-r-- 1 nick nick 4383 Mar 16 23:04 autoconfigure-azure-0.0.3-SNAPSHOT.pom
         -rw-rw-r-- 1 nick nick  931 Mar 16 23:04 maven-metadata-local.xml
 
        also note above .pom size diffs
 
 */
        presto(MavenPublication) {
            from components.java
        }
    }

    repositories {
        mavenLocal()
    }
}

dependencies {
    def springBootVersion = '3.4.3'
    
    def apacheCommonsLang3 = '3.17.0'
    def awaitility = '4.2.0'
    def azureActiveDirectory = '5.8.0'
    def googleGuava = '33.2.1-jre'
    def h2 = '2.2.224'
    def jacksonModuleAfterburner = '2.18.3'
    def lombok = '1.18.36'
    def springIntegrationSecurity= '6.2.9'

    implementation 'org.springframework.boot:spring-boot-starter:' + springBootVersion
    implementation 'org.springframework.boot:spring-boot-devtools:' + springBootVersion
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa:' + springBootVersion
    implementation 'org.springframework.boot:spring-boot-starter-validation:' + springBootVersion
    implementation 'org.springframework.boot:spring-boot-starter-websocket:' + springBootVersion
    implementation 'org.springframework.boot:spring-boot-starter-web:' + springBootVersion
    
    implementation 'org.springframework.boot:spring-boot-starter-security:' + springBootVersion
    implementation 'org.springframework.integration:spring-integration-security:' + springIntegrationSecurity
    
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-client:' + springBootVersion
    implementation 'com.azure.spring:spring-cloud-azure-starter-active-directory:' + azureActiveDirectory

    annotationProcessor 'org.springframework.boot:spring-boot-autoconfigure:' + springBootVersion
    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor:' + springBootVersion

    implementation 'com.h2database:h2:' + h2
    
    implementation 'org.apache.commons:commons-lang3:' + apacheCommonsLang3
    implementation 'com.fasterxml.jackson.module:jackson-module-afterburner:' + jacksonModuleAfterburner
    implementation 'com.google.guava:guava:' + googleGuava
    implementation 'org.projectlombok:lombok:' + lombok
    annotationProcessor 'org.projectlombok:lombok:' + lombok

    testImplementation 'org.springframework.boot:spring-boot-starter-test:' + springBootVersion
    testImplementation 'org.projectlombok:lombok:' + lombok
    testImplementation 'org.awaitility:awaitility:' + awaitility
    testAnnotationProcessor 'org.projectlombok:lombok:' + lombok

    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.1'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.1'
}

tasks.bootJar {
    enabled = false
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.withType(Javadoc).configureEach {
    options.encoding = 'UTF-8'
}

tasks.named('test') {
    useJUnitPlatform()
}

//test {
//    retry {
////        failOnPassedAfterRetry = true
//        maxRetries = 2
////        maxFailures = 42
//    }
//}
