buildscript {
    repositories {
        maven {
            url = 'https://plugins.gradle.org/m2/'
        }
    }
    dependencies {
        classpath 'com.adarshr:gradle-test-logger-plugin:4.0.0'
    }
}

rootProject.name = 'presto'

//include(':lib')

include ':lib:azure'
include ':lib:core'
include ':lib:h2db'
include ':lib:jpa'
include ':lib:ldap'
include ':lib:mysql'
include ':lib:nostr'
include ':lib:web'

include(':autoconfigure')
//include(':autoconfigure-azure')
//include(':autoconfigure-core')
//include(':autoconfigure-h2db')
//include(':autoconfigure-jpa')
//include(':autoconfigure-ldap')
//include(':autoconfigure-mysql')
//include(':autoconfigure-nostr')
//include(':autoconfigure-web')

include(':starter')
//include(':starter-azure')
//include(':starter-core')
//include(':starter-h2db')
//include(':starter-jpa')
//include(':starter-ldap')
//include(':starter-mysql')
//include(':starter-nostr')
//include(':starter-web')
