plugins {
    id 'buildlogic.java-conventions'
}

dependencies {
    api project(':autoconfigure-ldap')
    api project(':lib-ldap')
}

description = 'presto-ldap-spring-boot-starter'

publishing {
    publications {
        maven(MavenPublication) {
            artifactId = description
            from(components.java)
        }
    }
}
