plugins {
    id 'presto.java-conventions'
    id 'groovy-gradle-plugin'
    id 'org.gradle.test-retry'
}

description = 'lib-nostr'

dependencies {
    api project(':lib')
    api project(':lib-web')

    def springBootVersion = '3.4.3'

    testImplementation 'org.springframework.boot:spring-boot-starter-test:' + springBootVersion
}

tasks.register('integrationTest', Test) {
    description = 'lib integration tests.'
    group = 'verification'
    systemProperty("spring.profiles.active", "test")
    useJUnitPlatform()
    filter {
        excludeTestsMatching("*Test");
        includeTestsMatching("*IT");
    }
}

integrationTest {
    retry {
        failOnPassedAfterRetry = false
        maxRetries = 1
    }
}

check.dependsOn integrationTest
