plugins {
    id 'presto.java-conventions'
    id 'com.adarshr.test-logger'
    id 'org.gradle.test-retry'
}

group = 'com.prosilion.presto'
version = '0.0.3-SNAPSHOT'
description = 'lib-nostr'

dependencies {
    api project(':lib')
    api project(':lib-web')

    def springBootVersion = '3.4.3'
    def awaitility = '4.2.0'
    def lombok = '1.18.36'

    testImplementation 'org.springframework.boot:spring-boot-starter-test:' + springBootVersion
    testImplementation 'org.projectlombok:lombok:' + lombok
    testImplementation 'org.awaitility:awaitility:' + awaitility
    testAnnotationProcessor 'org.projectlombok:lombok:' + lombok
}

tasks.register('integrationTest', Test) {
    description = 'lib integration tests.'
    group = 'verification'
    systemProperty("spring.profiles.active", "test")
    useJUnitPlatform()
    filter {
        excludeTestsMatching("*Test");
        includeTestsMatching("*IT");
    }
}

integrationTest {
    retry {
        failOnPassedAfterRetry = false
        maxRetries = 1
    }
}

check.dependsOn integrationTest
