plugins {
    id 'presto.java-conventions'
}

dependencies {
//    implementation project(':lib')
    api project(':lib-web')
}

tasks.register('libNostrIntegrationTest', Test) {
    description = 'lib-nostr integration tests.'
    group = 'verification'
    systemProperty("spring.profiles.active", "test")
    useJUnitPlatform()
    filter {
        excludeTestsMatching("*Test");
        includeTestsMatching("*IT");
    }
}

check.dependsOn libNostrIntegrationTest
