plugins {
    id 'buildlogic.java-conventions'
}

dependencies {
    api project(':lib-h2db')
}

description = 'autoconfigure-h2db'

dependencies {
    def h2Version = '2.2.224'
    
    implementation 'com.h2database:h2:' + h2Version
}

publishing {
    publications {
        maven(MavenPublication) {
            artifactId = description
            from(components.java)
        }
    }
}

bootJar {
    enabled = false
}
