plugins {
    id 'presto.java-conventions'
}

description = 'autoconfigure-ldap'

dependencies {
    def springBootVersion = '3.4.3'
    def springLdapCore = '3.2.1'
    def springSecurityLdap = '6.2.1'

    api project(':lib-core')
    api project(':lib-web')
    api project(':lib-ldap')
    
    implementation 'org.springframework.boot:spring-boot-starter-data-ldap:' + springBootVersion
    implementation 'org.springframework.ldap:spring-ldap-core:' + springLdapCore
    implementation 'org.springframework.security:spring-security-ldap:' + springSecurityLdap
    
}
