plugins {
    id 'buildlogic.java-conventions'
}

description = 'autoconfigure-jpa'

dependencies {
    api project(':lib-core')
    api project(':lib-web')
    api project(':lib-jpa')
}

publishing {
    publications {
        maven(MavenPublication) {
            artifactId = description
            from(components.java)
        }
    }
}
