plugins {
    id 'buildlogic.java-conventions'
}

dependencies {
    api project(':autoconfigure-mysql')
    api project(':lib-mysql')
}

description = 'presto-mysql-spring-boot-starter'

publishing {
    publications {
        maven(MavenPublication) {
            artifactId = description
            from(components.java)
        }
    }
}
