plugins {
    id 'presto.java-conventions'
    id 'groovy-gradle-plugin'
    id 'com.adarshr.test-logger'
    id 'org.gradle.test-retry'
}

group = 'com.prosilion.presto'
version = '0.0.3-SNAPSHOT'
description = 'lib'

dependencies {
    def springBootVersion = '3.4.3'
    implementation 'org.springframework.boot:spring-boot-gradle-plugin:' + springBootVersion
}
