plugins {
    id 'buildlogic.java-conventions'
}

description = 'autoconfigure-mysql'

dependencies {
    api project(':lib-mysql')
    
    def mysqlConnectorJ= '9.1.0'
    
    implementation 'com.mysql:mysql-connector-j:' + mysqlConnectorJ
}

publishing {
    publications {
        maven(MavenPublication) {
            artifactId = description
            from(components.java)
        }
    }
}
