plugins {
    id 'buildlogic.java-conventions'
}

description = 'presto-web-spring-boot-starter'

dependencies {
    api project(':autoconfigure-web')
    api project(':lib-web')
}

publishing {
    publications {
        maven(MavenPublication) {
            artifactId = description
            from(components.java)
        }
    }
}
