plugins {
    id 'buildlogic.java-conventions'
}

dependencies {
    api project(':autoconfigure-core')
    api project(':lib-h2db')
}

description = 'presto-core-spring-boot-starter'

publishing {
    publications {
        maven(MavenPublication) {
            artifactId = description
            from(components.java)
        }
    }
}
