plugins {
    id 'buildlogic.java-conventions'
}

description = 'presto-h2db-spring-boot-starter'

dependencies {
    api project(':autoconfigure-h2db')
    api project(':lib-h2db')
}

publishing {
    publications {
        maven(MavenPublication) {
            artifactId = description
            from(components.java)
        }
    }
}
