plugins {
    id 'java'
    id 'java-library'
    id 'groovy-gradle-plugin'
}

group = 'com.prosilion.presto'
version = '0.0.3-SNAPSHOT'
description = 'presto'

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    gradlePluginPortal()
    mavenLocal()
    mavenCentral()
    maven {
        url = uri('https://repo.maven.apache.org/maven2/')
    }
}

dependencies {
    def springBootVersion = '3.4.3'
    def snakeYamlVersion = '2.2'

    implementation 'org.springframework.boot:spring-boot:' + springBootVersion
    implementation 'org.springframework.boot:spring-boot-gradle-plugin:' + springBootVersion

    implementation 'org.yaml:snakeyaml:' + snakeYamlVersion

    testImplementation 'org.springframework.boot:spring-boot-starter-test:' + springBootVersion
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}

//test {
//    retry {
////        failOnPassedAfterRetry = true
//        maxRetries = 2
////        maxFailures = 42
//    }
//}

