plugins {
    id 'java-library'
    id 'groovy-gradle-plugin'
}

group = 'com.prosilion.presto'
version = '0.0.3-SNAPSHOT'

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    gradlePluginPortal()
    mavenCentral()
    maven {
        url = uri('https://repo.maven.apache.org/maven2/')
    }
}

dependencies {
    def springBootVersion = '3.4.3'
    def snakeYamlVersion = '2.2'

    implementation 'org.springframework.boot:spring-boot:' + springBootVersion
    implementation 'org.springframework.boot:spring-boot-gradle-plugin:' + springBootVersion
    implementation 'org.yaml:snakeyaml:' + snakeYamlVersion
}

test {
    useJUnitPlatform()
}
