plugins {
    id 'buildlogic.java-conventions'
}

description = 'lib-h2db'

dependencies {
    def h2Version = '2.2.224'
    runtimeOnly 'com.h2database:h2:' + h2Version
}

publishing {
    publications {
        maven(MavenPublication) {
            artifactId = description
            from(components.java)
        }
    }
}

